#!/usr/bin/env sh
update='1'
IFS="$(printf ' \t\n|')"
IFS="${IFS%'|'}"
command clear
command clear
printf '                 .___       __\n __ ________   __\174 _\057____ _\057  \174_  ____\n\174  \174  \134____ \134 \057 __ \174\134__  \134\134   __\134\057 __ \134\n\174  \174  \057  \174_\076 \076 \057_\057 \174 \057 __ \134\174  \174 \134  ___\057\n\174____\057\174   __\057\134____ \174\050____  \057__\174  \134___  \076\n      \174__\174        \134\057     \134\057          \134\057\n a Lucas Larson production\n\n' && command sleep 1
unset PS4
printf '\360\237\223\241  verifying network connectivity'
command sleep 1
i='0'
while test "${i-}" -lt "$(printf '2 ^ 7 + 1\n' | command bc)"; do
  if test "$((i / 3 % 2))" -eq '0'; then printf '.'; else printf '\b'; fi
  i="$((i + 1))"
done
unset i
printf '\n\n'
{ command ping -c 1 -- one.one.one.one >/dev/null 2>&1 && command ping -c 1 -- 8.8.8.8 >/dev/null 2>&1; } || {
  update="${?-}"
  printf 'No internet connection detected.\nAborting update.\n'
  return "${update:-1}"
}
printf '\360\237\215\272  checking for Homebrew installation...'
if command -v -- brew >/dev/null 2>&1; then
  printf '  \342\234\205  found\n'
  printf '\360\237\215\272  checking for Homebrew updates...\n'
  command brew update
  command brew upgrade --greedy
  command brew upgrade --cask --greedy
  command brew install --debug --verbose --HEAD --display-times --git -- git
  command brew install --debug --verbose --HEAD --display-times --git -- mackup
  command brew install --debug --verbose --HEAD --display-times --git -- shellcheck
  command brew install --debug --verbose --HEAD --display-times --git -- shfmt
  command brew install --debug --verbose --HEAD --display-times --git -- zsh
else printf 'No Homebrew installation detected.\n\n'; fi
printf '\360\237\217\224  checking for Alpine Package Keeper installation...\n'
if command -v -- apk >/dev/null 2>&1; then
  printf '\360\237\217\224  apk update...\n'
  command apk update --progress --verbose --verbose
  printf '\n\360\237\217\224  apk upgrade...\n'
  command apk upgrade --update-cache --progress --verbose --verbose
  printf '\n\360\237\217\224  apk fix...\n'
  command apk fix --progress --verbose --verbose
  printf '\n\360\237\217\224  apk verify...\n'
  command apk verify --progress --verbose --verbose
  printf '\360\237\217\224  apk verify complete...\n\n'
else printf 'no Alpine Package Keeper installation detected.\n\n'; fi
printf 'checking access to Software Update...\n'
if command -v -- softwareupdate >/dev/null 2>&1; then
  printf '\360\237\215\216  '
  command softwareupdate --list --all --verbose
else printf 'no Software Update installation detected.\n\n'; fi
printf 'checking for Xcode installation...\n'
if command -v -- xcrun >/dev/null 2>&1; then
  printf 'removing unavailable device simulators...\n'
  command xcrun simctl delete unavailable
else printf 'no Xcode installation detected.\n\n'; fi
printf '\342\232\233\357\270\217  checking for Atom installation...\n'
if command -v -- apm >/dev/null 2>&1; then command apm upgrade --no-confirm; else printf 'no Atom installation detected.\n\n'; fi
printf 'checking for Rust installation...\n'
if command -v -- rustup >/dev/null 2>&1; then command rustup --verbose update; else printf 'no Rust installation detected.\n\n'; fi
printf 'checking for npm installation...\n'
if command -v -- npm >/dev/null 2>&1; then
  printf '...and whether this device is can update Node quickly...\n'
  if test "$((${COLUMNS:-80} * ${LINES:-24}))" -ge "$((80 * 24))"; then
    while test -n "$(command find -- "${HOME-}"'/.npm-packages' -type f -name '.DS_Store' -print)"; do command find -- "${HOME-}"'/.npm-packages' -type f -name '.DS_Store' -print -delete; done
    command npm install npm --location=global
    while test -n "$(command find -- "${HOME-}"'/.npm-packages' -type f -name '.DS_Store' -print)"; do command find -- "${HOME-}"'/.npm-packages' -type f -name '.DS_Store' -print -delete; done
    command npm update --location=global --loglevel=verbose
  else
    printf 'skipping Node update...\n\n'
    command sleep 1
    printf 'to update Node later, run:\n\n'
    printf '    npm install npm --location=global \046\046 \134\n'
    printf '    npm update --location=global --loglevel=verbose\n\n\n'
    command sleep 3
  fi
else printf 'no npm installation detected.\n\n'; fi
printf 'checking for RubyGems installation...\n'
if command -v -- gem >/dev/null 2>&1; then
  printf 'updating RubyGems...\n'
  command gem update --system --verbose
  command gem update --verbose
  if command bundle update >/dev/null 2>&1; then command bundle update --verbose 2>/dev/null; fi
  if command bundle install >/dev/null 2>&1; then command bundle install --verbose 2>/dev/null; fi
  printf 'checking for CocoaPods installation...\n'
  if command bundle exec pod install >/dev/null 2>&1; then command bundle exec pod install --verbose 2>/dev/null; fi
  if command pod repo update >/dev/null 2>&1; then
    command pod repo update --verbose
    command pod repo update --verbose
  fi
else printf 'no RubyGems installation detected.\n\n'; fi
if command -v -- rbenv >/dev/null 2>&1; then command rbenv rehash; fi
if command -v -- c_rehash >/dev/null 2>&1; then command c_rehash; fi
if command -v -- python3 >/dev/null 2>&1; then
  printf '\n\360\237\220\215  verifying Python\342\200\231s packager is up to date...\n'
  command python3 -m pip install --upgrade --verbose --verbose --verbose -- pip
  printf 'verifying pip installation...\n'
  if command -v -- pip >/dev/null 2>&1; then
    printf '\n\360\237\220\215  updating outdated Python packages...\n'
    command pip list --outdated --format freeze | while IFS='' read -r package; do command pip install --upgrade --verbose --verbose --verbose -- "${package%%=*}"; done
    unset package
  fi
  printf 'checking for pyenv installation...\n'
  if command -v -- pyenv >/dev/null 2>&1; then
    printf 'rehashing pyenv shims...\n'
    command pyenv rehash
  else printf 'no pyenv installation detected.\n\n'; fi
  printf 'checking for Conda installation...\n'
  if command -v -- conda >/dev/null 2>&1; then command conda update --yes --all; else printf 'no Conda installation detected.\n\n'; fi
fi
command brew generate-man-completions --debug --verbose 2>/dev/null
command brew bundle dump --all --cask --debug --describe --file=- --force --formula --mas --tap --verbose --whalebrew | command sed -e '$!N;/^#.*\n[^#]/s/\n/\t/;P;D' | command awk -F '\t' -- '{print $2 $1}' | command sed -E -e 's/^(tap)/1\1/' -e 's/^(brew)/2\1/' -e 's/^(cask)/3\1/' | LC_ALL='C' command sort -f | command sed -e 's/^[[:digit:]]//' | command sed -e 's/\([^#]*\)\(#.*\)/\2\n\1/' >"${HOME-}"'/.Brewfile'
if command -v -- omz >/dev/null 2>&1; then omz update 2>/dev/null; fi
# shellcheck source=/dev/null
test -r "${HOME-}"'/.'"${SHELL##*[-./]}"'rc' && . "${HOME-}"'/.'"${SHELL##*[-./]}"'rc'
if command -v -- rehash >/dev/null 2>&1; then rehash; fi
unset update
printf '\n\342%s\234\205  update complete\n' "${update-}"
"$(command -v -- exec)" -l -- "${SHELL##*[-./]}"
